version: '3.8'

services:
  telegram-userbot:
    image: registry.rptr.dev/synth-bot:latest
    container_name: telegram-userbot-app
    ports:
      - "8000:8000"
    volumes:
      - telegram_sessions:/app/sessions
      - telegram_data:/app/data
      - telegram_logs:/app/logs
      - telegram_temp:/app/temp
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - PYTHONUNBUFFERED=1
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-1440}
      - DEBUG=${DEBUG:-False}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-nw
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-nw:
    external: true

volumes:
  telegram_sessions:
    driver: local
  telegram_data:
    driver: local
  telegram_logs:
    driver: local
  telegram_temp:
    driver: local
