version: '3.8'

services:
  telegram-userbot:
    build: .
    container_name: telegram-userbot-app
    ports:
      - "8000:8000"
    volumes:
      - ./sessions:/app/sessions
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
