version: '3.8'

# Development docker-compose with bind mounts for easier development
services:
  telegram-userbot-local:
    build: .
    container_name: telegram-userbot-local
    ports:
      - "8000:8000"
    volumes:
      # Bind mounts for local development
      - ./sessions:/app/sessions
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
      - .:/app  # Mount entire project for live code changes
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - PYTHONUNBUFFERED=1
      - DEVELOPMENT=1
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - telegram-network

networks:
  telegram-network:
    driver: bridge
